### ISSUE TITLE
Allow to rebind device driver on Allocate

### ISSUE THREAD

**Issue by przemeklal** [k8snetworkplumbingwg/sriov-network-device-plugin#202]
## What would you like to be added?

Bind device to the kernel module (driver) of choice, specified in the resource configuration, during resource allocation.

## What is the use case for this feature / enhancement?

This way, the devices wouldn't need to be preconfigured/pre-bound before starting the device plugin - instead we'd have a new **optional** configuration field e.g. "targetDriver" and the device would be bound to either userspace or kernel driver dynamically. If the option is present we re-bind the driver and then allocate resource as usually, if not - we keep it bound to the current driver, so there's no change for existing deployments and configurations.

This feature has been proposed during brainstorming in the Network Service Mesh community as a useful enhancement in the DP, that could further improve synergy between NSM and Device Plugin.

**Comment by przemeklal** [comment]
@ahalim-intel @zshi-redhat thoughts?

Also tagging @edwarnicke here as this was mostly his idea :)

**Comment by ahalim-intel** [comment]
Hi @przemeklal, this is an old problem we have faced with device plugin API limitation. Ideally, we would like to do things like - allocate request would allow passing runtime configs and then we could take care of drivers binding at runtime, on demand.
Since, DP API do not provide this mechanism and there's no such plan to extend it that way - we left with creating specific VF resource pool before device plugin is launched. So, binding the right driver before launch or during launch don't make much difference. On allocate response we able to detect what driver the VF is attached to and we can export appropriate device files etc. that needed for that VF to be usable in container. Since it doesn't make any difference whether we do this in the device plugin or outside - we decided to leave driver binding outside of device plugin's scopes. Because it make sense to bind drivers when VFs are created. As you know this already, this is being done with some ansible scripts or using some operator.

Other alternative I could think of is leaving the driver binding for runtime. When allocate request coming from a specific endpoint for example "intel.com/x710-vfio-pci" we bind the vfio-pci driver to that VF and update all other endpoints device list which may also register the same VF. But with this we lose flexibility of using custom resource endpoint names.

**Comment by edwarnicke** [comment]
@ahalim-intel We actually do have a use case for this with [NSM](https://networkservicemesh.io/).  

NSM allows a Pod to request connectivity to a particular Network Service (think connectivity/security/etc) at runtime (throughout the lifecycle of the Pod).  NSM plumbs a 'vWire' from the consuming Pod to whatever is providing that Network Service.   We allow the Pod to specify a preference ordered list of the 'Mechanisms' it would like to be inserted for its end of the vWire.  Examples: kernel interface, vfio, memif, etc.  We are quite flexible on that point.

Might help if I give an example :)

Imagine I have a High Frequency Trading (HFT) application I'm deploying in my Pod.  I want it to be able to access the 'low-latency-to-NASDAQ' network service (note, we are handling making sure the right network service is provided by the physical network).   Further imagine that I've got the current version which uses kernel interfaces, and a new even faster version that uses vfio.  If the device plugin supports rebind on allocate, we set that in the DP to the vfio drivers, and those will be injected as devices into the Pod.  If the Pod then requests via NSM the kernel interface, the NSM Forwarder can do the rebind to kernel interface as part of setting up the network connectivity and inject that kernel interface into the Pod.

*But* ... when that SRIOV VF gets reallocated, we need it to be properly rebound to the vfio driver... because while we can insert a kernel interface (we do it all the time), we don't want to be in the business inserting device files, munging cgroups, etc.  We'd rather leave that to you guys.

You can imagine in the example why you don't actually want to be splitting your scarce and expensive resource (SRIOV VFs that are capable of connecting to the 'low-latency-to-nasdaq' network service) into static groups by driver... because NSM can handle dynamic mechanisms just fine.  We have the technology :)

Does that make sense?

**Comment by edwarnicke** [comment]
>Other alternative I could think of is leaving the driver binding for runtime. When allocate request coming from a specific endpoint for example "intel.com/x710-vfio-pci" we bind the vfio-pci driver to that VF and update all other endpoints device list which may also register the same VF. But with this we lose flexibility of using custom resource endpoint names.

Yeah... NSM has its own notion of resource naming ( ${network service domain}/${capability} ) where ${network service domain} is a whole collection of Network Services the Pod *might* choose to request that we can provide (think dc12.example.com representing the Network Services available in the dc12 of example.com) and ${capability} is something representing the capabilities of the SRIOV VF (like 10g, or mlx5).  So requiring driver info in the resource string also strikes us as a bad plan.

**Comment by ahalim-intel** [comment]
@edwarnicke I understood the usecase. The problem with the proposed "targetDriver" flag is as below:

For example, we have initially created 2 pools of VFs, 4 with vfio("intel.com/x710-vfio") and 4 with kernel driver("intel.com/x710-kernel"). We launch device plugin with "targetDriver"="vfio-pci"(I assume that is the real intent here). Any request coming to "intel.com/x710-vfio" no need to re-bind driver as it's the same. But request coming to "intel.com/x710-kernel" will now bind to vfio-pci before response is sent. Device plugin has no way of knowing when the VF is released. So, "intel.com/x710-kernel" will either update device list indicating it has one less device with kernel driver. And doing this, eventually, this endpoint will have no device left to allocate even though all previously allocated devices were returned by Kubelet. On the other hand, the endpoint "intel.com/x710-vfio" will have more devices but only registered 4. This approach will misaligned the actual resource accounting.

I think we need to find better solution than this.

**Comment by edwarnicke** [comment]
@ahalim-intel If you are using the resource string to encode drivers, you obviously wouldn't configure rebinding on allocate, as you've intrinsically decided on static drivers.  In the NSM case, you would simply have one pools of vfs:

"dc12.example.com/10g: 8"

The default binding is vfio (rebind-on-allocate), but if a Pod ask for:

"dc12.example.com/10g: 1" 

The device plugin inserts it as a vfio, and its job is done.

If that Pod then requests "low-latency-to-nasdaq@dc12.example.com" as a network service via NSM with a requested 'Mechanism' of kernel interface... NSM will rebind the issued PCI device to a kernel interface and insert that into the Pods network namespace.  

Time goes by, and the Pod goes away, a new Pod gets allocated the same deviceId for "dc12.example.com/10g", and it needs to be rebound to the default (vfio) device.

All we are asking for here is an *optional* configuration parameter to request 'rebind-to-driver-on-allocate' and specify the driver.  No config parameter, no change in behavior.

So as you can see, you *only* have a scheduling issue here *iff* you are embedding the driver into the resource name, which we are not and are not advocating for :)

**Comment by mdr78** [comment]
@edwarnicke 

So essential there is one pool and re-assign the driver based on the PODs rqmts, that makes sense.

**Comment by ahalim-intel** [comment]
> @ahalim-intel If you are using the resource string to encode drivers, you obviously wouldn't configure rebinding on allocate, as you've intrinsically decided on static drivers. In the NSM case, you would simply have one pools of vfs:
> 
> "dc12.example.com/10g: 8"
> 
> The default binding is vfio (rebind-on-allocate), but if a Pod ask for:
> 
> "dc12.example.com/10g: 1"
> 
> The device plugin inserts it as a vfio, and its job is done.
> 
> If that Pod then requests "[low-latency-to-nasdaq@dc12.example.com](mailto:low-latency-to-nasdaq@dc12.example.com)" as a network service via NSM with a requested 'Mechanism' of kernel interface... NSM will rebind the issued PCI device to a kernel interface and insert that into the Pods network namespace.
> 

So, you are suggesting here to depend on NSM  when the interface is used with regular kernel module. This breaks the compatibility with existing CNI plugin that does not behave the same way as you've described the NSM does.

> Time goes by, and the Pod goes away, a new Pod gets allocated the same deviceId for "dc12.example.com/10g", and it needs to be rebound to the default (vfio) device.

Since, NSM can handle the kernel interface and rebinding of drivers then why don't we just use one single pool with all vfio and let NSM do it's job? So, on pod deletion NSM need to ensure that kernel interface rebound to vfio-pci. No changes needed in device plugin and it does not break compatibility with CNI plugin.

> 
> All we are asking for here is an _optional_ configuration parameter to request 'rebind-to-driver-on-allocate' and specify the driver. No config parameter, no change in behavior.
> 
> So as you can see, you _only_ have a scheduling issue here _iff_ you are embedding the driver into the resource name, which we are not and are not advocating for :)

**Comment by edwarnicke** [comment]
> @edwarnicke
> 
> So essential there is one pool and re-assign the driver based on the PODs rqmts, that makes sense.

Exactly!

**Comment by edwarnicke** [comment]
@ahalim-intel 
> So, you are suggesting here to depend on NSM when the interface is used with regular kernel module. This breaks the compatibility with existing CNI plugin that does not behave the same way as you've described the NSM does.

I am not suggesting that Device Plugin 'depend' on NSM at all.  Device Plugin remains completely ignorant of NSM.  All it knows is that it has been asked to rebind to a particular driver on allocate.

This also is completely compatible with CNI.  NSM takes great care *not* to break CNI, and has CI across all of the major public cloud providers and vanilla K8s.  NSM is *orthogonal* to CNI.

> 
> > Time goes by, and the Pod goes away, a new Pod gets allocated the same deviceId for "dc12.example.com/10g", and it needs to be rebound to the default (vfio) device.
> 
> Since, NSM can handle the kernel interface and rebinding of drivers then why don't we just use one single pool with all vfio and let NSM do it's job? 
Because NSM doesn't get the Allocate call for the device, the device plugin does.  *Something* has to do the rebind to the vfio driver so that the SRIOV DP has the device to insert into the Pod.  The DP gets the event that indicates that should be done.

NSM could of course simply write its own DP to handle SRIOV, but we feel that you guys have done a good job, and we'd prefer not to see fracturing in this space.

>So, on pod deletion NSM need to ensure that kernel interface rebound to vfio-pci. No changes needed in device plugin and it does not break compatibility with CNI plugin.

Nothing we are asking for actually breaks CNI.  If you don't want rebind, you don't configure rebind for that resource, and you are good.

**Comment by ahalim-intel** [comment]
> @ahalim-intel
> 
> > So, you are suggesting here to depend on NSM when the interface is used with regular kernel module. This breaks the compatibility with existing CNI plugin that does not behave the same way as you've described the NSM does.
> 
> I am not suggesting that Device Plugin 'depend' on NSM at all. Device Plugin remains completely ignorant of NSM. All it knows is that it has been asked to rebind to a particular driver on allocate.
> 
> This also is completely compatible with CNI. NSM takes great care _not_ to break CNI, and has CI across all of the major public cloud providers and vanilla K8s. NSM is _orthogonal_ to CNI.
> 
> > > Time goes by, and the Pod goes away, a new Pod gets allocated the same deviceId for "dc12.example.com/10g", and it needs to be rebound to the default (vfio) device.
> > 
> > 
> > Since, NSM can handle the kernel interface and rebinding of drivers then why don't we just use one single pool with all vfio and let NSM do it's job?
> > Because NSM doesn't get the Allocate call for the device, the device plugin does.  _Something_ has to do the rebind to the vfio driver so that the SRIOV DP has the device to insert into the Pod.  The DP gets the event that indicates that should be done.
> 
> NSM could of course simply write its own DP to handle SRIOV, but we feel that you guys have done a good job, and we'd prefer not to see fracturing in this space.
> 

What I am saying is, as you have stated, if NSM could do the binding to kernel driver from vfio then it could also possibly bind it back to vfio when the Pods gets deleted. If that is possible then device plugin does not need to do the rebinding and from it's point of view devices remain the same as it has registered originally.

> > So, on pod deletion NSM need to ensure that kernel interface rebound to vfio-pci. No changes needed in device plugin and it does not break compatibility with CNI plugin.
> 
> Nothing we are asking for actually breaks CNI. If you don't want rebind, you don't configure rebind for that resource, and you are good.

If device plugin is running with "targetDriver" in conjunction with traditional Multus+SR-IOV-CNI. As described here, the device plugin will rebind the kernel interface pool also to vfio upon allocate request. The SR-IOV CNI wouldn't know the difference and treat this VF as a regular vfio device as it sees it. But in Pod, it was requested from a kernel interface pool. You've mentioned NSM is well able to make decision on what interface type by looking at the resource endpoint name. The same mechanism does not exist with current CNI implementation. That's why this approach is not compatible with existing CNI plugin.

**Comment by zshi-redhat** [comment]
> @edwarnicke I understood the usecase. The problem with the proposed "targetDriver" flag is as below:
> 
> For example, we have initially created 2 pools of VFs, 4 with vfio("intel.com/x710-vfio") and 4 with kernel driver("intel.com/x710-kernel"). We launch device plugin with "targetDriver"="vfio-pci"(I assume that is the real intent here). Any request coming to "intel.com/x710-vfio" no need to re-bind driver as it's the same. But request coming to "intel.com/x710-kernel" will now bind to vfio-pci before response is sent. Device plugin has no way of knowing when the VF is released. So, "intel.com/x710-kernel" will either update device list indicating it has one less device with kernel driver. And doing this, eventually, this endpoint will have no device left to allocate even though all previously allocated devices were returned by Kubelet. On the other hand, the endpoint "intel.com/x710-vfio" will have more devices but only registered 4. This approach will misaligned the actual resource accounting.
> 

I share the same concern as @ahalim-intel that DP doesn't get notified when a device is released from Pod. If we were to support dynamic binding of driver, we will need to think about solution how to re-bind the same devcie back to its original pool, instead of relying on external component to do the re-binding.

> I think we need to find better solution than this.

+!

**Comment by zshi-redhat** [comment]
Some dirvers (e.g mlx5_core) doesn't require particular driver binding in order to work in dpdk mode, where you might not be able to use `targetDirver` to specify whether this is a high-performance resource or regular resource.

Support binding of `vfio-pci` driver may require other changes to make it intact and self-contained in DP, there are other system configs to enable the binding, for example: to load the kernel module, to enable iommu in the kernel argument (e.g. in kubeVirt case). I feel these configurations shall be considered as well when enabling dynamic binding as we probably don't want to see DP gets crashed or `targetDirver` not be applied until creating a pod. But on the other hand, we already have established solution to handle these configuration.

**Comment by davecremins** [comment]
Ultimately, this is a good ask and something that should be supported in the long term. However, seeing as the existing implementation splits the resources into their respective pools, the flag to target a different driver will create confusion in terms of source of truth between the semantics of the pod and the **actual** allocation. Even though most of the configurations will be ignorant of a **targetDriver** flag, its the cases where this flag is leveraged that literally changes the canonical behavior of the DP resulting in a degree of grayness.

An alternative might be to allow for a "mode of operation" whereby the DP acts on a single pool and wires up the target driver as per the ask. This way the concern of allocation from pool remains unchanged and **targetDriver** flag becomes mandatory.

For now, I think we need to go back to the drawing board on this one.

**Comment by davecremins** [comment]
Leaving open for now to cater for alternative suggestions

**Comment by edwarnicke** [comment]
> Ultimately, this is a good ask and something that should be supported in the long term. However, seeing as the existing implementation splits the resources into their respective pools, the flag to target a different driver will create confusion in terms of source of truth between the semantics of the pod and the **actual** allocation. Even though most of the configurations will be ignorant of a **targetDriver** flag, its the cases where this flag is leveraged that literally changes the canonical behavior of the DP resulting in a degree of grayness.

I guess the fundamental question here is what the canonical behavior of the DP is.  Resetting the device to a known good initial state is the motherhood and apple pie of what a DP does.  So the question is:

Is this a generic SRIOV DP, or is it a CNI SRIOV DP?

What is its canonical nature :)

**Comment by martinkennelly** [comment]
Closing because this issue is stale.
