### ISSUE TITLE
delete custom resource on k8s

### ISSUE THREAD

**Issue by thanhlong9x** [k8snetworkplumbingwg/sriov-network-device-plugin#275]
Hi, I have question about custom resoures. After I delete configMap of sr-iov device, I check on master node but custom resource not delete.So, how to delete them ? 
See my image below:
![image](https://user-images.githubusercontent.com/29721257/96427094-53de4700-1228-11eb-8cfb-138a460de320.png)

**Comment by adrianchiris** [comment]
Device plugin does not act on config map updates, you need to restart(delete) the device plugin pod.

**Comment by thanhlong9x** [comment]
@adrianchiris  Yes, I restarted  the device plugin pod but its not working

**Comment by adrianchiris** [comment]
@thanhlong9x let me make sure i understand the issue you are facing.

A resource was defined in device plugin config Map and device plugin reported it to kubelet, then you deleted that resource from device plugin config map and restarted device plugin. Now Kubelet still reports that resource with zero devices available instead of removing it?

**Comment by adrianchiris** [comment]
from a quick skim through kubelet code i think it just mark a resource as unhealthy (set its capacity/allocatable to zero) it does not remove the resource from the node when the device plugin resource socket is deleted.

https://github.com/kubernetes/kubernetes/blob/2570a9d94ced1954edfe4cbf3b84200f126ab717/pkg/kubelet/cm/devicemanager/manager.go#L332

**Comment by amorenoz** [comment]
I believe it is a known issue: https://github.com/kubernetes/kubernetes/issues/92396

**Comment by martinkennelly** [comment]
Closing due to known issue with kubelet. No changes required to SRIOV DP code.
