### ISSUE TITLE
Travis may break because of anon docker account

### ISSUE THREAD

**Issue by martinkennelly** [k8snetworkplumbingwg/sriov-network-device-plugin#319]
### What happened?
During our travis CI script phase, we use an anon docker account when executing "make image". I have seen this fail: https://travis-ci.org/github/k8snetworkplumbingwg/sriov-network-device-plugin/builds/756409635

It seems pulling the image didn't work due to missing Travis CI docker build cache [1] and if it misses the cache, we pull from docker anonymously with limits placed on travis IPs.
It worked fine on retry of test.

### What did you expect to happen?
Image pull to be deterministic in travis CI

There is discussion at NPWG level about solving the docker image limit issue. I propose, we use the nfvpe account until that discussion is resolved.

[1] https://blog.travis-ci.com/docker-rate-limits

**Comment by zshi-redhat** [comment]
Martin, thanks for reporting the issue!
I remember seeing this failure several times locally, didn't know it also fails in CI, was thinking it might be due to my own docker account limit.
I noticed there was a discussion about this in plumbing working group meeting, what's the conclusion? are we going to change the image registry or trying to solve the issue with docker registry?

**Comment by martinkennelly** [comment]
Travis is no longer supported. Closing.
