### ISSUE TITLE
 docker.io/nfvpe/sriov-device-plugin:ppc64le cannot be pulled due to "manifest unknown"

### ISSUE THREAD

**Issue by chenliu1993** [k8snetworkplumbingwg/sriov-network-device-plugin#358]
## What issue would you like to bring attention to?
I am trying to pull  docker.io/nfvpe/sriov-device-plugin:ppc64le, but I got this error:
```
docker pull  docker.io/nfvpe/sriov-device-plugin:ppc64le
Error response from daemon: manifest for nfvpe/sriov-device-plugin:ppc64le not found: manifest unknown: manifest unknown
```
Will  this image be removed from daemonset?
Thanks for help.
## Do you have a proposed response or remediation for the issue?

**Comment by zshi-redhat** [comment]
ppc64le image build was disabled in this [commit](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/commit/d00ca6625385412501929ab98e7940ed3eb8883b) due to build failure. I checked the nfvpe/sriov-device-plugin repo and didn't find the ppc64le image tag. 

btw, we are adding new image build via github action in [PR](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/pull/348), which will replace the nfvpe one. I think it will solve the issue once merged.

**Comment by chenliu1993** [comment]
Cool! Thank you for the infomation.
